# Copyright (c) 2019, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'

environment:
  ATF_VERSION: 2.1

install:
  - sh: sudo apt-get update -qq
  - sh: sudo -E apt-get install -y gcc-aarch64-linux-gnu

before_build:
  - ps: Start-FileDownload https://github.com/ARM-software/arm-trusted-firmware/archive/v$env:ATF_VERSION.tar.gz
  - sh: tar -xzf v$ATF_VERSION.tar.gz

build_script:
  - sh: cd arm-trusted-firmware-$ATF_VERSION
  - sh: export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-
  - sh: make PLAT=rpi3 PRELOADED_BL33_BASE=0x30000 RPI3_PRELOADED_DTB_BASE=0x10000 SUPPORT_VFP=1 RPI3_USE_UEFI_MAP=1 fip all

after_build:
  - sh: sha256sum build/rpi3/release/bl1.bin
  - sh: sha256sum build/rpi3/release/fip.bin

artifacts:
  - path: arm-trusted-firmware-$(ATF_VERSION)/build/rpi3/release/bl1.bin
    name: BL1 image
    type: file
  - path: arm-trusted-firmware-$(ATF_VERSION)/build/rpi3/release/fip.bin
    name: FIP image
    type: file

deploy:
  release: v$(ATF_VERSION)
  description: Raspberry Pi 3 Arm Trusted Firmware v$(ATF_VERSION)
  provider: GitHub
  auth_token:
    secure: w5YuQOim+G+U7FxxrL0BH6t0trCWKCs9DMZlF4xqF2XGC6SymzwaJrPWrKeeJHPK
  artifact: /.*\.bin/
  draft: false
  prerelease: false
