# ATF version to build (must match an ATF release tag)
version: 2.1
image: Ubuntu1804
install:
  - sh: sudo apt-get update -qq
  - sh: sudo -E apt-get install -y gcc-aarch64-linux-gnu
before_build:
  - ps: Start-FileDownload https://github.com/ARM-software/arm-trusted-firmware/archive/v$env:APPVEYOR_BUILD_NUMBER.tar.gz
  - sh: tar -xzvf v$APPVEYOR_BUILD_VERSION.tar.gz
build_script:
  - sh: >-
      cd $APPVEYOR_BUILD_VERSION
      export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-
      make PLAT=rpi3 PRELOADED_BL33_BASE=0x30000 RPI3_PRELOADED_DTB_BASE=0x10000 SUPPORT_VFP=1 RPI3_USE_UEFI_MAP=1 fip all
artifacts:
  - path: build/rpi3/release/bl1.bin
    name: bl1.bin
    type: file
  - path: build/rpi3/release/fip.bin
    name: fip.bin
    type: file
